version: '3.4'

services:
  editor-db:
    image: postgres:12.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: editor_local

  editor-app:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      args:
        BUNDLE_ARGS: ''
    tty: true
    stdin_open: true
    ports:
      - 9090:3000
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgres://postgres:password@editor-db/editor_local"
      RAILS_LOG_TO_STDOUT: 'true'
      ENCODED_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEA+OtquVq4iSKV6xTibO3snW70AK0/ILG/vDt8KNCQNf/411D7\nh+F3Kpw+vNANfHdJTfJUV4/dYz5HHsAxAaG8qyHiNycy9cNsHoRCold5Zp8iEBkS\ncXOSh32qKD6e0brwJvpyv0QcHWfKZz46PBm6TUxrC6z9nwiePQX/sryFhpzX8sL7\nD09Qwc1c/42PHhLkxvcCioHhj33zT+YOCNvI5RyYPG6lKvn1QSKvSJ+zoAnwP7R7\nL7c/QixADzleAq7HNEhE8p0T0OVegWa85Ox7fK9j/vZw9bFYOK1CVNQcf+VGh2Fa\ngs/7D9T0nrhQ3xKxpKvnfzVoqga38V7gWZyt8QIDAQABAoIBAQDtpYyh49w0iQGK\ni8jU6J4zfB+WmdCgPTNp2XzjVqOn+ncv0lAiXX6w/rTi/NszTot80HP3mRFrU6UA\n1cqz3R9MXzAjKdh8TJPn2qvnZA4yjJEvv1AdYpKtqqsOeyKT556qCAgPVU5mQJY7\n1WwxvvpgHCpC3mjRMaApcJW7pkLwzOFTiP3B5EYMfPMGJfqPsQYFhRXlft0fC77Y\nADosRuU5IFQbQHENo22PLD+BJ2vY7i/RiOrVhUg9wGjFAU+ghXIdO6BgbMEV7+Dw\nagw6WJfS81cH3RFU6ZwJqDANzrfRRMxebH2WLtbE4iSFeBEpvCV2T6VCDRvPoNbO\n4ATOMzYBAoGBAP6GeamkUYZcIrB0oWZBoFsUmaKxMrEDaoQZ7QFFICEAJWvyUEzI\n4WUILskeK7RnFmfrYPeuCK8D//EZUi3j77DXjOFoSc2/Q10/FVoXPPj1xp2Uo5zZ\nxc0apU3KNL4vvMo7ZHcDO17hy7UDfN6CxmutuE93MXHbQiypN0AC9GVhAoGBAPpc\noIKr86PPs5qF++vTYvAvqGTmQ5JG1hddF1rR4IOS/6MoMZ1pB2+ETFVum/2/gwi9\n4iuARiEbE+imvaDRDIMQ6e1M5CFtRA19y703JwieeLFrzNgNp0CwJB9H+SQj9Z0P\nfeOU3u+nyFwnfGA/lBxaNu3eJmHYlre5hsI6NIKRAoGAM2iL6ETFJqMzanqUIug8\ncEkP4vlxaKls+TOXWDtTCvdRl6UArRGh3NszP/H1F+H+d4zmMACZxmfDaToZDCXO\nwuQ2k0ySI5lvDMVyFZk9+ncB39Am38Zomk24d6bQ0l0n/5zRZOxlMHvgvjXvIa4+\nT39uC7biaMHFcunWu/oczOECgYADLanb/tLZAYoGLC1GkShwZCp/HW0+LigJo+To\nAkIXaYZVS+1VUkAF6mgNrZnNXuEK+14jrz00rmNSUMuXfw/pmg1eNduvkPOMOEyd\n2lVkhp6Bohy3oXS+HX5X51ICY3J6y/eNLBaodDjW8qlhj20R7xNDcc6K73T6YCCV\n1qdUAQKBgHMT8rQMzmCRusDPc2Dl/qjDT/rDQ1iMQQNQB2yvg6z41QgAhb90mOB4\nY8i256sOPWYqRymxq40FR0ZFkW/y1cceceVpjWvhS5ZrjgLmDbZnSUQnMafUNgNy\nK0VWsiR2LxJCBgiw0evtz+W2GOYpOhgpep5AjLITla5FsZUSNI3c\n-----END RSA PRIVATE KEY-----"
      METADATA_API_URL: "http://editor-metadata-app:3000/"
      PLATFORM_ENV: "local"
      SECRET_KEY_BASE: "2de1e1ddc4dc9eebb238d35d6b131cd76c481adb6371ded658fa259411379431391e9431e6257d1ea9dccb80df5d693904b6a4ed3bec7984647fd79c86bf4db5"
    depends_on:
      - editor-db
      - editor-metadata-app

  editor-metadata-db:
    image: postgres:12.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: metadata_local

  editor-metadata-app:
    build:
      context: https://github.com/ministryofjustice/fb-metadata-api.git#main
      args:
        BUNDLE_ARGS: ''
    tty: true
    stdin_open: true
    ports:
      - 9091:3000
    environment:
      DATABASE_URL: "postgres://postgres:password@editor-metadata-db/metadata_local"
      RAILS_ENV: test
      SERVICE_TOKEN_CACHE_ROOT_URL: 'http://editor-service-token-cache-app:3000'
      MAX_IAT_SKEW_SECONDS: '60'
      RAILS_LOG_TO_STDOUT: 'true'
    depends_on:
      - editor-metadata-db
      - editor-service-token-cache-app

  editor-service-token-cache-app:
    container_name: editor-service-token-cache-app
    build:
      context: https://github.com/ministryofjustice/fb-service-token-cache.git
    environment:
      SENTRY_DSN: sentry-dsn
      RAILS_ENV: test
      RAILS_LOG_TO_STDOUT: 'true'
      REDIS_URL: editor-service-token-cache-redis
      SERVICE_TOKEN_CACHE_TTL: 999999
    depends_on:
      - editor-service-token-cache-redis
    ports:
      - 9092:3000

  editor-service-token-cache-redis:
    container_name: editor-service-token-cache-redis
    image: redis:5.0.6-alpine
