version: 1

update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
    - tomas-stefano
    - brenetic
    - mattempty
    - njseeto
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
    - mattempty
    - form-builder-developers
    - tomas-stefano
    - brenetic
    - njseeto
  - package_manager: "docker"
    directory: "/docker/web"
    update_schedule: "daily"
    default_reviewers:
    - tomas-stefano
    - brenetic
    - mattempty
    - njseeto
  - package_manager: "docker"
    directory: "/docker/workers"
    update_schedule: "daily"
    default_reviewers:
    - tomas-stefano
    - brenetic
    - mattempty
    - njseeto
  - package_manager: "docker"
    directory: "/acceptance"
    update_schedule: "daily"
    default_reviewers:
    - tomas-stefano
    - brenetic
    - mattempty
    - njseeto
