apiVersion: v1
kind: ConfigMap
metadata:
  name: fb-editor-config-map
  namespace: formbuilder-saas-{{ .Values.environmentName }}
data:
  RAILS_ENV: production
  RAILS_LOG_TO_STDOUT: "true"
  PLATFORM_ENV: {{ .Values.environmentName }}
  RAILS_SERVE_STATIC_FILES: "true"
  AUTH0_DOMAIN: mojds-trial.eu.auth0.com
  EDITOR_FULL_URL_ROOT: https://fb-editor-{{ .Values.environmentName }}.apps.live-1.cloud-platform.service.justice.gov.uk
  ENCODED_PUBLIC_KEY: {{ .Values.encoded_public_key }}
  METADATA_API_URL: http://fb-metadata-api-svc-{{ .Values.environmentName }}
