---
# front-end
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "fb-editor-web-{{ .Values.environmentName }}"
  namespace: formbuilder-saas-{{ .Values.environmentName }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "fb-editor-web-{{ .Values.environmentName }}"
  template:
    metadata:
      labels:
        app: "fb-editor-web-{{ .Values.environmentName }}"
        appGroup: "fb-editor"
        fb-service-token-cache-access: "true"
        tier: "frontend"
    spec:
      containers:
      - name: "fb-editor-web-{{ .Values.environmentName }}"
        image: "754256621582.dkr.ecr.eu-west-2.amazonaws.com/formbuilder/fb-editor-web:{{ .Values.circleSha1 }}"
        volumeMounts:
        - mountPath: /tmp
          name: tmp-files
        securityContext:
          runAsUser: 1001
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        # non-secret env vars
        # defined in config_map.yaml
        envFrom:
          - configMapRef:
              name: fb-editor-config-map
        env:
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: secret_key_base
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: sentry_dsn
          - name: AUTH0_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: auth0_client_id
          - name: AUTH0_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: auth0_client_secret
          - name: ENCODED_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: encoded_private_key
          - name: ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: encryption_key
          - name: ENCRYPTION_SALT
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: encryption_salt
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: rds-instance-formbuilder-editor-{{ .Values.environmentName }}
                key: url
          - name: EDITOR_SERVICE_ACCOUNT_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.editor_service_account_token }}
                key: token
          - name: SUBMISSION_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: submission_encryption_key
          - name: SERVICE_SENTRY_DSN_TEST
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: service_sentry_dsn_test
          - name: SERVICE_SENTRY_DSN_LIVE
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: service_sentry_dsn_live
      volumes:
        - name: tmp-files
          emptyDir: {}
---
# workers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "fb-editor-workers-{{ .Values.environmentName }}"
  namespace: formbuilder-saas-{{ .Values.environmentName }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "fb-editor-workers-{{ .Values.environmentName }}"
  template:
    metadata:
      labels:
        app: "fb-editor-workers-{{ .Values.environmentName }}"
        appGroup: "fb-editor"
        fb-service-token-cache-access: "true"
        tier: "frontend"
    spec:
      securityContext:
        runAsUser: 1001
      serviceAccountName: "formbuilder-editor-workers-{{ .Values.environmentName }}"
      containers:
      - name: "fb-editor-workers-{{ .Values.environmentName }}"
        image: "754256621582.dkr.ecr.eu-west-2.amazonaws.com/formbuilder/fb-editor-workers:{{ .Values.circleSha1 }}"
        volumeMounts:
        - mountPath: /tmp
          name: tmp-files
        securityContext:
          runAsUser: 1001
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        # non-secret env vars
        # defined in config_map.yaml
        envFrom:
          - configMapRef:
              name: fb-editor-config-map
        env:
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: secret_key_base
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: sentry_dsn
          - name: AUTH0_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: auth0_client_id
          - name: AUTH0_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: auth0_client_secret
          - name: ENCODED_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: encoded_private_key
          - name: ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: encryption_key
          - name: ENCRYPTION_SALT
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: encryption_salt
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: rds-instance-formbuilder-editor-{{ .Values.environmentName }}
                key: url
          - name: EDITOR_SERVICE_ACCOUNT_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.editor_service_account_token }}
                key: token
          - name: SUBMISSION_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: submission_encryption_key
          - name: SERVICE_SENTRY_DSN_TEST
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: service_sentry_dsn_test
          - name: SERVICE_SENTRY_DSN_LIVE
            valueFrom:
              secretKeyRef:
                name: fb-editor-secrets-{{ .Values.environmentName }}
                key: service_sentry_dsn_live
      volumes:
        - name: tmp-files
          emptyDir: {}
